(function () {
    "use strict";
    const content = window.STM_GUIDE_CONTENT;
    if (!content || window.STM_FIELD_MANUAL) return;
    const positions = [[12,14],[39,29],[72,18],[87,72],[57,66],[25,78]];
    let chapterIndex = 0, opener = null, previousBodyOverflow = "";
    const el = {};
    const make = (tag, className, text) => { const node=document.createElement(tag); if(className)node.className=className;if(text!==undefined)node.textContent=text;return node; };
    const button = (label, className="stm-guide-button") => { const node=make("button",className,label);node.type="button";return node; };
    function build() {
        el.overlay=make("div","stm-guide");el.overlay.id="stmFieldManual";el.overlay.hidden=true;el.overlay.setAttribute("role","dialog");el.overlay.setAttribute("aria-modal","true");el.overlay.setAttribute("aria-labelledby","stmGuideTitle");
        const shell=make("div","stm-guide-shell");const head=make("header","stm-guide-head");el.title=make("h1","stm-guide-title",content.title);el.title.id="stmGuideTitle";head.append(el.title,make("span","stm-guide-version",`MANUAL ${content.version}`));el.counter=make("span","stm-guide-counter");el.close=button("CLOSE","stm-guide-close");head.append(el.counter,el.close);
        const main=make("div","stm-guide-main");el.nav=make("nav","stm-guide-nav");el.nav.setAttribute("aria-label","Manual chapters");const toc=make("div","stm-guide-toc");content.chapters.forEach((chapter,index)=>{const b=button(`${chapter.number} // ${chapter.title}`,"");b.dataset.index=String(index);toc.append(b)});el.nav.append(toc);
        const selectWrap=make("div","stm-guide-select-wrap");el.select=make("select","stm-guide-select");el.select.setAttribute("aria-label","Manual chapter");content.chapters.forEach((chapter,index)=>{const option=make("option","",`${chapter.number} // ${chapter.title}`);option.value=String(index);el.select.append(option)});selectWrap.append(el.select);
        el.scroller=make("main","stm-guide-content");el.scroller.tabIndex=0;main.append(el.nav,selectWrap,el.scroller);
        const foot=make("footer","stm-guide-foot");el.previous=button("PREVIOUS");el.next=button("NEXT");el.top=button("BACK TO TOP");foot.append(el.previous,el.next,el.top);
        shell.append(head,main,foot);el.overlay.append(shell);document.body.append(el.overlay);
        el.lightbox=make("div","stm-guide-lightbox");el.lightbox.hidden=true;el.lightbox.setAttribute("role","dialog");el.lightbox.setAttribute("aria-modal","true");const lbHead=make("div","stm-guide-lightbox-head");el.lbTitle=make("div","stm-guide-lightbox-title");el.lbClose=button("CLOSE","stm-guide-close");lbHead.append(el.lbTitle,el.lbClose);el.lbScroll=make("div","stm-guide-lightbox-scroll");el.lightbox.append(lbHead,el.lbScroll);document.body.append(el.lightbox);
        bind();
    }
    function noteNode(text) { const type=/^(CAUTION|IMPORTANT|NOTE):/.exec(text)?.[1]||"NOTE";const node=make("div",`stm-guide-note ${type.toLowerCase()}`);const strong=make("strong","",`${type}: `);node.append(strong,document.createTextNode(text.replace(/^(CAUTION|IMPORTANT|NOTE):\s*/,"")));return node; }
    function block(title,value,ordered=false){const section=make("section","stm-guide-block");section.append(make("h3","",title));if(Array.isArray(value)){const list=make(ordered?"ol":"ul");value.forEach(item=>list.append(make("li","",item)));section.append(list)}else section.append(make("p","",value));return section;}
    function figure(chapter){const fig=make("figure","stm-guide-figure");const shot=make("button","stm-guide-shot");shot.type="button";shot.setAttribute("aria-label",`Enlarge ${chapter.title} screenshot`);const img=make("img");img.src=chapter.image;img.alt=`Controlled fixture view: ${chapter.title}`;img.loading="lazy";shot.append(img);chapter.callouts.forEach((_,i)=>{const c=make("span","stm-guide-callout",String(i+1));c.style.left=`${positions[i%positions.length][0]}%`;c.style.top=`${positions[i%positions.length][1]}%`;shot.append(c)});const cap=make("figcaption","stm-guide-caption",`CONTROLLED FIXTURE // ${chapter.title} // CLICK TO ENLARGE`);const list=make("ol","stm-guide-callout-list");chapter.callouts.forEach((textValue,i)=>{const li=make("li");li.append(make("b","",String(i+1)),document.createTextNode(textValue));list.append(li)});fig.append(shot,cap,list);shot.addEventListener("click",()=>openLightbox(chapter));return fig;}
    function render(index,focus=false){chapterIndex=Math.max(0,Math.min(content.chapters.length-1,index));const chapter=content.chapters[chapterIndex];el.scroller.replaceChildren();const article=make("article","stm-guide-chapter");article.append(make("div","stm-guide-kicker",`${chapter.number} // FIELD MANUAL`),make("h2","",chapter.title),block("PURPOSE",chapter.purpose),block("CONTROLS",chapter.controls),block("HOW IT WORKS",chapter.how),block("PERSISTENCE",chapter.persistence),block("SAFETY NOTES",chapter.safety),figure(chapter));chapter.notes.forEach(value=>article.append(noteNode(value)));if(chapterIndex===content.chapters.length-1){const glossary=make("section","stm-guide-glossary");glossary.append(make("h3","","GLOSSARY"));const dl=make("dl");content.glossary.forEach(([term,definition])=>{dl.append(make("dt","",term),make("dd","",definition))});glossary.append(dl);article.append(glossary)}el.scroller.append(article);el.scroller.scrollTop=0;el.counter.textContent=`${chapter.number} / ${String(content.chapters.length).padStart(2,"0")}`;el.previous.disabled=chapterIndex===0;el.next.disabled=chapterIndex===content.chapters.length-1;el.select.value=String(chapterIndex);el.nav.querySelectorAll("button").forEach((b,i)=>{b.classList.toggle("active",i===chapterIndex);b.setAttribute("aria-current",i===chapterIndex?"page":"false")});if(focus)(chapterIndex===0?el.next:el.previous).focus();}
    function open(){if(!el.overlay)build();opener=document.activeElement;previousBodyOverflow=document.body.style.overflow;document.body.classList.add("stm-guide-scroll-lock");el.overlay.hidden=false;render(0);el.close.focus();}
    function close(){if(el.lightbox&&!el.lightbox.hidden){closeLightbox();return}el.overlay.hidden=true;document.body.classList.remove("stm-guide-scroll-lock");document.body.style.overflow=previousBodyOverflow;opener?.focus?.();}
    function openLightbox(chapter){el.lbTitle.textContent=`${chapter.number} // ${chapter.title}`;const figure=make("div","stm-guide-lightbox-figure");const img=make("img");img.src=chapter.image;img.alt=`Enlarged controlled fixture view: ${chapter.title}`;figure.append(img);chapter.callouts.forEach((_,i)=>{const c=make("span","stm-guide-callout",String(i+1));c.style.left=`${positions[i%positions.length][0]}%`;c.style.top=`${positions[i%positions.length][1]}%`;figure.append(c)});el.lbScroll.replaceChildren(figure);el.lightbox.hidden=false;el.lbClose.focus();}
    function closeLightbox(){el.lightbox.hidden=true;el.lbScroll.replaceChildren();el.scroller.querySelector(".stm-guide-shot")?.focus();}
    function trap(event,root){if(event.key!=="Tab")return;const nodes=[...root.querySelectorAll("button:not([disabled]),select,[tabindex='0']")].filter(n=>n.getClientRects().length);if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
    function bind(){el.close.addEventListener("click",close);el.lbClose.addEventListener("click",closeLightbox);el.previous.addEventListener("click",()=>render(chapterIndex-1,true));el.next.addEventListener("click",()=>render(chapterIndex+1,true));el.top.addEventListener("click",()=>{el.scroller.scrollTo({top:0,behavior:"smooth"});el.top.focus()});el.nav.addEventListener("click",e=>{const target=e.target.closest("button[data-index]");if(target)render(Number(target.dataset.index))});el.select.addEventListener("change",()=>render(Number(el.select.value)));el.overlay.addEventListener("pointerdown",e=>{if(e.target===el.overlay)close()});el.lightbox.addEventListener("pointerdown",e=>{if(e.target===el.lightbox||e.target===el.lbScroll)closeLightbox()});document.addEventListener("keydown",e=>{if(!el.lightbox.hidden){if(e.key==="Escape"){e.preventDefault();closeLightbox()}else trap(e,el.lightbox);return}if(!el.overlay.hidden){if(e.key==="Escape"){e.preventDefault();close()}else trap(e,el.overlay)}});}
    document.addEventListener("DOMContentLoaded",()=>{build();const trigger=document.getElementById("guideTrigger");if(trigger)trigger.addEventListener("click",open)} ,{once:true});
    window.STM_FIELD_MANUAL=Object.freeze({open,close,get chapter(){return chapterIndex;}});
}());
